name: Create Release

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            ## Install

            ```bash
            npm i -g @easy-base/docs-mcp
            ```

            See [README.md](https://github.com/base-kit/docs-mcp#readme) for full capabilities.
